### PR TITLE
fix(almin): export UseCaseExecutor from index

### LINKED ISSUE #206: Almin: lifecyle method in UseCaseExectutor will be deprecated.
These method are deprecated in 0.13.0 next version.

- `UseCaseExectutor#onWillExecuteEachUseCase`
- `UseCaseExectutor#onDidExecuteEachUseCase`
- `UseCaseExectutor#onCompleteExecuteEachUseCase`

You can use `Context` method insteadof it.

### PR DESCRIPTION
**Pull request by azu**
BREAKING CHANGE: remove on* handler from UseCaseExecutor.
Use UseCaseExecutor#onDispatch instead of it.

We don't know this handler use-case.

If you want to this, please file new issue.

---

- export `UseCaseExecutor` from index

This is useful for wrapper function of `context.useCase`

```js
/**
 * Extends React.Component for Container.
 * It has executor feature for almin UseCase.
 */
export class BaseContainer<T, P> extends React.Component<T, P> {
    useCase<T extends UseCase>(useCase: T): UseCaseExecutor<T> {
        return appLocator.context.useCase(useCase);
    }
}
```

- https://github.com/azu/faao/blob/master/src/component/container/BaseContainer.ts

fix #206

### CODE REVIEW

File: packages/almin/src/UseCaseExecutor.ts [hunk 1]
```diff
@@ -220,56 +220,10 @@ export class UseCaseExecutor<T extends UseCaseLike> extends Dispatcher {
...
         // It prevent leaking of instance.
         UseCaseInstanceMap.delete(this.useCase);
-        this.emit("COMPLETE");
     }
 
-    /**
-     * called the {@link handler} with useCase when the useCase will do.
-     * @param   handler
-     */
-    onWillExecuteEachUseCase(handler: (payload: WillExecutedPayload, meta: DispatcherPayloadMeta) => void): () => void {
```
Comment (azu) [inline packages/almin/src/UseCaseExecutor.ts]: remove life-cycle on UseCaseExecutor
