### PR TITLE
fix(almin): add warning to no-commit transaction

### LINKED ISSUE #240: almin: no-commit transaction should be warning
I've noticed that no-commit transaction is silent reset.
It make user confuse.

```js
    await appContext.transaction("bootstrap", async (transactionContext) => {
        // reset repository and observe changes
        await transactionContext.useCase(InitializeRepositoryUseCase.create()).execute();
        // Create anonymous customer data
        await transactionContext.useCase(InitializeCustomerUseCase.create()).execute();
        // use initialState if server-side provide
        // if initialState is not provided, client fetch products data
        const initialShopProducts = window.__PRELOADED_STATE__ ? window.__PRELOADED_STATE__ : undefined;
        await transactionContext.useCase(InitializeProductUseCase.create()).execute(initialShopProducts);
        // forget to commit!!!
    })
```

We want to preserve no-commit mode.

- Add `transactionContext.exit()` or `transactionContext.end()`
- If any `commit()` or `exit()` is not called, should show warning message: "this transaction is silent reset. If you want to no commit, please call `transactionContext.exit()`"

### PR DESCRIPTION
**Pull request by azu**
- Add `transactionContext.exit()` for evincive committment

Following case is invalid

```js
    await appContext.transaction("bootstrap", async (transactionContext) => {
        await transactionContext.useCase(InitializeCustomerUseCase.create()).execute();
        // forget to commit!!!
        // please commit() or exit()!!!
    })

/*
Warning(Transaction): Transaction(${this.name}) should be commit() or exit() at least one. 
If you not want to commit, Please call \`transactionContext.exit()\` at end of transaction.
*/
```

fix #240

### CODE REVIEW

File: packages/almin/src/Context.ts [hunk 1]
```diff
@@ -317,19 +327,32 @@ Please enable strict mode via \`new Context({ dispatcher, store, options: { stri
...
+        const promise = transactionHandler(context);
+        if (!promise) {
+            throw new Error(`transaction context should return promise.
+Transaction should be exited after all useCases have been completed.
+
+For example, following transaction will be exited after SomeUseCase is completed.
+
+context.transaction("transaction", transactionContext => {
+     return transactionContext.useCase(new SomeUseCase()).execute();
+});
```
Comment (azu) [inline packages/almin/src/Context.ts]: add check return value is a promise

File: packages/almin/src/Context.ts [hunk 2]
```diff
@@ -317,19 +327,32 @@ Please enable strict mode via \`new Context({ dispatcher, store, options: { stri
...
+        }
+        return promise.then(
             () => {
-                unitOfWork.endTransaction();
                 unitOfWork.release();
             },
             error => {
-                unitOfWork.endTransaction();
                 unitOfWork.release();
                 return Promise.reject(error);
```
Comment (azu) [inline packages/almin/src/Context.ts]: release auromaically end
